server:
  port: 8080
  env: development

database:
  host: localhost
  port: 5432
  user: postgres
  password: 77072166
  name: erp_system
  sslmode: disable

jwt:
  secret: "your-256-bit-secret-key-here"
  expiration: 3600 # 1小时 